### ISSUE TITLE
Create a guide to setting up Apache Guacamole and Enclave

### ISSUE THREAD

**Issue by enclave-marc-barry** [enclave-networks/docs#31]
## Invisible bastion host for AWS

Azure has a service called Bastion, but due to configuration it frequently times out when using it for RDS. Our customer is running on AWS and ideally want a drop-in equivalent Apache Guacamole and Enclave that "just works".

He's tried to set this up himself and run into issue after issue. This is a fantastic opportunity for us to do proactive customer enablement and help him (and others who follow) to just deploy Enclave into a really useful scenario.

The concept is to achieve a fully self-contained bastion host with no open / listening ports. The customer just wants to consume the bastion host using the Enclave interface, no ports open on other interfaces.

## Objectives

- [ ] Instructions to setup Apache Guacamole using Docker to provide access into a local network
- [ ] Instructions to provide remote access Enclave
- [ ] Instructions to deploy using a serverless technology in AWS
- [ ] Instructions for what deem to be best practise for such a deployment (i.e. settings on the host, settings in docker etc)

## Quality check

- [ ] Must be able to follow the article with minimal (or no) changes and arrive at a working deployment
- [ ] Provide sensible defaults and easy (working) copy-paste docker file examples

## Notes and context from the customer

```
Guacamole build was based on this https://www.howtoforge.com/how-to-install-apache-guacamole-as-docker-container-on-ubuntu/

I abandoned it due to performance issues but I had some critical issues with UFW/IPtables that also made it unviable. There is a known issue with Docker where it manipulates IPtables itself therefore 'ignores' UFW rules. After some experimentation I got the Docker to bind to loopback only. I meant to use IPtables to forward traffic from the tap0 interface but took an easier route with Nginx as a reverse proxy. Excuse my lack of IPtables and Docker knowledge.

The Docker/UFW issue is documented in https://github.com/docker/for-linux/issues/690

The aim here was to have a remote management node with Guacamole/SSH ports only accessible via the Enclave connector. With no other way of controlling inbound traffic (NSG), this had to be done on the host itself through IPtables. In practice, deploying a gateway node is probably simpler for us in this case.

Other challenges that remain (generally) are DNS and proxying Kerberos - both of these are issues within traditional Windows networks where clients typically have full access to a domain controller but not the case where accessing individual servers with Enclave directly - client needs a TGT/TGS to authenticate to a file server or RDS where NLA is enabled. Assuming in a secured environment you block NTLM downgrade for at least your privileged users ('protected users' group), this becomes a problem. For example, I have a non-domain (AAD native-joined) device and I am attempting to access a domain-joined Windows box over RDP - this fails unless NLA is disabled. It is possible I will need to implement https://syfuhs.net/kdc-proxy-for-remote-access to address that issue.

You possibly need to look at DNS forwarding to address internal resource access
```

**Comment by enclave-tom** [comment]
Leaving my notes here

# Notes
This example uses Guacamole but in reality and service can be deployed like this.

Create a folder called `guacamoleCompose` then do the below

This example is how we get Guacamole running. At this stage you won't be able to access it as we've not exposed the ports and we won't be as we'll be routing all access to these services over enclave.
```yaml
version: '3.1'
services:
  guacd:
    container_name: guacd
    image: guacamole/guacd
    restart: always
    volumes:
    - ./drive:/drive:rw
    - ./record:/record:rw
  postgres:
    container_name: postgres_guacamole
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
    image: postgres:13.4-buster
    restart: always
    volumes:
    - ./init:/docker-entrypoint-initdb.d:z
    - ./data:/var/lib/postgresql/data:Z
  guacamole:
    container_name: guacamole
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
    image: guacamole/guacamole
    restart: always
```

Once we've put the above code into our `docker-compose.yml` file and change the `POSTGRES_PASSWORD` values to ones we're happy with we can continue.

Now we can add the enclave fabric container this will be our entry point. We recommend using an ephemeral key for docker containers and assigning it it's own DNS through tags. This means you can always access it via the same DNS setting regardless of the ID of the container as this will no doubt change as it's a container.

```yaml
  enclave-fabric:
    container_name: fabric
    image: enclavenetworks/enclave:latest
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      ENCLAVE_ENROLMENT_KEY: QPW9R-HHWGE-GCEEK-L4ELZ-7XT66
    volumes:
      - enclave-config:/etc/enclave/profiles
      - enclave-logs:/var/log/enclave
volumes:
  enclave-config:
  enclave-logs:
```

We can add this to the end of the `docker-compose.yml`

now all we need to do is add `network_mode: service:enclave-fabric` to the `guacamole` service as below. This tells the guacamole container to send traffic over the enclave fabric container.
```yaml
  guacamole:
    container_name: guacamole
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
    image: guacamole/guacamole
    network_mode: service:enclave-fabric
    restart: always
```

Okay and finally we need to run the below script. this will setup the first run sql script needed to populate the postgres container. You can do this by running 
```bash
nano prepare.sh
```

then pasting the below script and saving by pressing `ctrl + x`
```bash
#!/bin/sh
#
# check if docker is running
if ! (docker ps >/dev/null 2>&1)
then
	echo "docker daemon not running, will exit here!"
	exit
fi
echo "Preparing folder init and creating ./init/initdb.sql"
mkdir ./init >/dev/null 2>&1
chmod -R +x ./init
docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --postgres > ./init/initdb.sql
echo "done"
```
run 

```bash
chmod +x prepare.sh
./prepare.sh
```


now that's done you can run

```bash
docker compose up -d
```

Special thanks to [this repo](https://github.com/boschkundendienst/guacamole-docker-compose) for a super useful guide on setting up guacamole in docker compose

# Files
[docker-compose.zip](https://github.com/enclave-networks/docs/files/10434082/docker-compose.zip)
